Feature/asset classes docs
BirjuVachhani/spider pull request #56
Opened 2022-07-06 14:37 UTC by Sanlovty

### Description of the Change
Start asset-class file generation with ignore_rules

### Benefits
Follow linter rules ,no more warnings

### Verification Process
Generate asset-classes and analyze with linter

### Applicable Issues
Closes #55

2022-07-06 14:45 UTC, Sanlovty commented
**Update:** I can make this solution more interesting - we can allow user to pass the set of rules [first-rule, second-rules, third-rule] instead of hardcoding it ( sometimes user can set linter rules that include member sorting, so we will prevent this)

2022-07-10 15:58 UTC, BirjuVachhani requested changes

2022-07-10 15:58 UTC, BirjuVachhani commented on lib/src/data/export_template.dart
> +    '// ignore_for_file: public_member_api_docs, member-ordering-extended\n\n';
`member-ordering-extended` is not from official Flutter/Dart lints. We shouldn't add that I believe. Besides, I thought it was ordering references by name, wasn't it?

2022-07-10 16:04 UTC, Sanlovty commented on lib/src/data/export_template.dart
> +    '// ignore_for_file: public_member_api_docs, member-ordering-extended\n\n';
I added the idea to issue. We can allow user do add rules  list user want to be ignored in files

2022-07-10 16:08 UTC, BirjuVachhani commented on lib/src/data/export_template.dart
> +    '// ignore_for_file: public_member_api_docs, member-ordering-extended\n\n';
I like that idea!

2022-07-10 16:09 UTC, BirjuVachhani commented on lib/src/data/export_template.dart
> +    '// ignore_for_file: public_member_api_docs, member-ordering-extended\n\n';
This PR is redundant then, isn't it?

2022-07-10 16:10 UTC, Sanlovty commented on lib/src/data/export_template.dart
> +    '// ignore_for_file: public_member_api_docs, member-ordering-extended\n\n';
Yes, it was made before the idea. I'l make normal one later(tomorrow)

2022-07-10 16:17 UTC, BirjuVachhani commented on lib/src/data/export_template.dart
> +    '// ignore_for_file: public_member_api_docs, member-ordering-extended\n\n';
Alright then, closing this PR for now.

2022-07-10 16:17 UTC, closed without merging